"""
Django settings for ZAM project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lhf&qxb!18h4d9^d7^#!ae+a^6)+hycw6llx3*zo$rd+cxvpmx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#BEGUG = False

ALLOWED_HOSTS = ['*']

TEMPLATE_DIRS = (
    BASE_DIR+'/templates',
)

# Application definition
CAPTCHA_IMAGE_SIZE=(142,35)
CAPTCHA_FONT_SIZE=30
#CAPTCHA_FOREGROUND_COLOR='red'
#CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_CHALLENGE_FUNCT = 'zamapp.captcha_mod.random_digit_challenge'


TEMPLATE_DIRS = (
    BASE_DIR+'/templates',
    BASE_DIR+'/customerapp/templates',
)

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.core.context_processors.request',
    'django.contrib.auth.context_processors.auth',
)

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'zamapp',
    'captcha',
    'customerapp',
    'django.contrib.humanize'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'ZAM.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'ZAM.wsgi.application'

DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'zamfinal_db',
         'USER':'root',
         'PASSWORD':'root1234',
         'HOST':'zamsystemdb.c3yo9odujbrz.ap-southeast-1.rds.amazonaws.com',
         'PORT':'3306',
     }
}
#
# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        #'NAME': 'zam06062016_db',
#        'NAME': 'zam_new_db',
#        'USER':'root',
#        'PASSWORD':'root',
#        #'PASSWORD':'root1234',
#        'HOST':'localhost',
#        #'HOST':'zamsystemdb.c3yo9odujbrz.ap-southeast-1.rds.amazonaws.com',
#        'PORT':'3306',
#    }
# }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#STATIC_URL = '/static/'

STATICFILES_DIRS = ('assets', BASE_DIR +'/static/',)

MEDIA_ROOT = BASE_DIR+'/media/'

MEDIA_URL ='/media/'
